# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layoutWordProccessor1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wordProccessor(object):
    def setupUi(self, wordProccessor):
        wordProccessor.setObjectName("wordProccessor")
        wordProccessor.resize(978, 1318)
        wordProccessor.setStyleSheet("background-color: rgb(175, 236, 184);")
        self.centralwidget = QtWidgets.QWidget(wordProccessor)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 140, 801, 24))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.wordSearchFieldLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.wordSearchFieldLayout.setContentsMargins(0, 0, 0, 0)
        self.wordSearchFieldLayout.setObjectName("wordSearchFieldLayout")
        self.wordSearchField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.wordSearchField.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.wordSearchField.setObjectName("wordSearchField")
        self.wordSearchFieldLayout.addWidget(self.wordSearchField, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(900, 170, 23, 1131))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.verticalScrollBarLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.verticalScrollBarLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalScrollBarLayout.setObjectName("verticalScrollBarLayout")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.gridLayoutWidget_2)
        self.verticalScrollBar.setStyleSheet("")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.verticalScrollBarLayout.addWidget(self.verticalScrollBar, 0, 0, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(90, 170, 801, 1131))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.documentLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.documentLayout.setContentsMargins(0, 0, 0, 0)
        self.documentLayout.setObjectName("documentLayout")
        self.document = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        self.document.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.document.setObjectName("document")
        self.documentLayout.addWidget(self.document, 0, 0, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(-1, -1, 981, 131))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.menuLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.menuLayout.setContentsMargins(0, 0, 0, 0)
        self.menuLayout.setObjectName("menuLayout")
        wordProccessor.setCentralWidget(self.centralwidget)

        self.retranslateUi(wordProccessor)
        QtCore.QMetaObject.connectSlotsByName(wordProccessor)

    def retranslateUi(self, wordProccessor):
        _translate = QtCore.QCoreApplication.translate
        wordProccessor.setWindowTitle(_translate("wordProccessor", "Word Proccessor"))
